# Generated by Django 6.1.1 on 2026-09-14 19:29

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.CharField(blank=True, default="", max_length=50)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                (
                    "state",
                    models.CharField(blank=True, db_index=True, default="", max_length=2),
                ),
                ("rack_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "retail_price",
                    models.DecimalField(
                        db_index=True, decimal_places=8, default=0, max_digits=12
                    ),
                ),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "ordering": ["id"],
            },
        ),
    ]